### ISSUE TITLE
[개발] 일반 사용자 로그인 화면 FE/BE 연동

### ISSUE THREAD

**Issue by CEEDLIVE** [busy-joj/admin_equipment8#1]
## TODO
- [x] FE/BE 연동 (공통)
    - [x] API 연동을 위한 HTTP 통신 라이브러리 추가
        - [x] Axios 라이브러리 추가
- [ ] 화면 별 연동 작업
    - [ ] 로그인 화면
        - [x] 로그인 API 
            - [x] API 응답결과 처리
                - [x] 성공
                    - [x] 대시보드 메인 화면으로 이동
                - [x] 실패
                    - [x] 오류 메시지 출력
                        - [x] 미등록 계정
                        - [x] 비밀번호 오류
        - [x] 로그인 상태 유지
